export { default as Summary } from './summary/summary.component';
export { default as Cart } from './Cart/cart.component';
export { default as GroupPrivate } from './GroupPrivate/groupprivate.component';
export { default as Multiple } from './Multiple/multiple.component';
export { default as Price } from './Price/price.component';
export { default as LateralMenu } from './Lateral-Menu/lateral-menu.component';
export { default as Description } from './Description/description.component';
export { default as UploadPhotos } from './Upload-Photos/upload-photos.component';
export {default as WhatsIncluded} from './Whats-included/whats-included.component';
export { default as Meeting } from './Meeting/meeting.component';
export { default as Stops } from './Stops/stops.component';
export { default as Languages } from './Languages/languages.component';
export { default as Restrictions } from './Restrictions/restrictions.component';
export { default as ChildPolicy } from './ChildPolicy/childpolicy.component';
export { default as Assistance } from './Assistance/assistance.component';
export { default as Transportation } from './Transportation/transportation.component';
export { default as Restrooms } from './Restrooms/restrooms.component';
export {default as Places} from './Places/places.component';
export { default as Equipment } from './Equipment/equipment.component';
export { default as Faqs } from './FAQS/faqs.component';
